#!/usr/bin/env python3

import Pyrraform
from Pyrraform import tfplugin5_0_pb2


class AnswerDataSource(Pyrraform.DataSource):
    config_schema = Pyrraform.Schema(tfplugin5_0_pb2.Schema(
        block=tfplugin5_0_pb2.Schema.Block(attributes=[
            tfplugin5_0_pb2.Schema.Attribute(name="value", type=b'"number"'),
        ])
    ))

    def read(self):
        return {
            "value": 42,
        }

class SimpleDataSourceProvider(Pyrraform.Provider):
    data_source_classes = {
        "answer": AnswerDataSource,
    }


if __name__ == "__main__":
    Pyrraform.run_provider(SimpleDataSourceProvider)
