#!/usr/bin/env python3

import Pyrraform


class AnswerDataSource(Pyrraform.DataSource):
    config_schema = Pyrraform.Schema(
        version=0,
        block=Pyrraform.schema.Block(
            version=0,
            attributes=[
                Pyrraform.schema.Attribute(
                    name="value",
                    type=Pyrraform.Number,
                    description="",
                    required=False,
                    optional=False,
                    computed=False,
                    sensitive=False,
                ),
            ],
            block_types=[],
        )
    )

    def read(self):
        return {
            "value": 42,
        }


class SimpleDataSourceProvider(Pyrraform.Provider):
    data_source_classes = {
        "answer": AnswerDataSource,
    }


if __name__ == "__main__":
    Pyrraform.run_provider(SimpleDataSourceProvider)
